[build-system]
requires = ["setuptools>=80.9", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "vtt-converter"
version = "0.1.0"
description = "VTT Converter application"
authors = [
    {name = "Chris", email = "chris@onoo.no"}
]
requires-python = ">=3.11,<3.13"

dependencies = [
    "openai==2.5.0",
    "python-dotenv==1.1.1",
]

[project.scripts]
vtt = "src:main"

[project.optional-dependencies]
dev = [
    "ruff==0.14.1",
    "mypy==1.18.2",
]

[tool.ruff]
line-length = 100

# Zestaw reguł na start
lint.select = ["E", "F", "I", "UP", "B", "SIM"]
# E,F - błędy i styl PEP8
# I - sortowanie importów
# UP - unowocześnienia składni
# B - bugbear, typowe wpadki
# SIM - proste uproszczenia

[tool.ruff.lint.isort]
known-first-party = ["src"]

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]

[tool.mypy]
python_version = "3.12"
ignore_missing_imports = true
disallow_untyped_defs = true
check_untyped_defs = true
warn_unused_ignores = true
